### ISSUE TITLE
Nexe Bundle

### ISSUE THREAD

**Issue by ronag** [CasparCG/media-scanner#1]
Waiting for https://github.com/nexe/nexe/issues/418

**Comment by pkeuter** [comment]
Another, potentially interesting option is https://github.com/zeit/pkg.

**Comment by ronag** [comment]
@pkeuter try it and let us know! :)

**Comment by pkeuter** [comment]
Seems to work correctly.  Does it need to be implemented in the Docker container?

**Comment by ronag** [comment]
@pkeuter no, just update the npm scripts and you'r good! PR

**Comment by pkeuter** [comment]
Be aware that the native extensions (of Leveldown in this case) have to be placed along the binary for now, but it works.

**Comment by pkeuter** [comment]
See https://github.com/CasparCG/media-scanner/pull/2
