### ISSUE TITLE
Choice of language

### ISSUE THREAD

**Issue by dimitry-ishenko** [CasparCG/media-scanner#11]
Not trying to start a flame war, but I am curious why was Node.js chosen for this?

It seems C++ + asio + filesystem (merged in c++17) would be more in the spirit of the CasparCG project.

**Comment by ronag** [comment]
Because it's **a lot** easier to build in NodeJS.

**Comment by ronag** [comment]
Just building a proper filesystem watch module would take half a month, then database integration etc... there is no advantage with using c++ for this functionality. The right tool for the right job :).

**Comment by dimitry-ishenko** [comment]
> Just building a proper filesystem watch module would take half a month

Not necessarily. There are several ready-made solutions. Eg, `dir_monitor` based on `asio`. Plus, there is always `QFilesystemWatcher` if you don't mind adding Qt to the list of dependencies.

> then database integration

Again, there is a number of c++ wrappers on top of sqlite and other databases. Plus, there is always `QSqlDatabase`. :smile: 

> there is no advantage with using c++ for this functionality

I am not a big fan loosely-typed and interpreted languages, so I would beg to differ here.

**Comment by ronag** [comment]
> I am not a big fan loosely-typed and interpreted languages, so I would beg to differ here.

loosely-typed and interpreted languages => good productivity, low performance
strong-typed and compiled languages => poor productivity, high performance

The only typed language that I would consider worth using in terms of correctness is rust. But that has even worse productivity.

What you win in types with C++ you lose in undefined behavior. If this was a system critical component I would probably have picked TypeScript.
