### ISSUE TITLE
Websocket data endpoint

### ISSUE THREAD

**Issue by Julusian** [CasparCG/media-scanner#15]
There is no way for a client to be notified of new media without polling the scanner at regular intervals.

By having a websocket endpoint in the scanner, clients who want real-time media updates could connect directly (not via AMCP) and get them streamed.

**Comment by ronag** [comment]
Or just connect to the couchdb database directly?

**Comment by Julusian** [comment]
Having never used pouchdb before, as far as I can tell, the database isn't currently exposed, and I don't see  a simple way to expose the change stream 'natively'

**Comment by ronag** [comment]
`pouchdb-server`
