### ISSUE TITLE
Unable to build master

### ISSUE THREAD

**Issue by Julusian** [CasparCG/media-scanner#23]
It is currently not possible to build scanner due to an incompatibility between pkg and a dependency of express-pouchdb (pouchdb-fauxton).

This means we can't build scanner until something is fixed upstream or we revert the change which added express-pouchdb.
Alternatively, as the dependency causing the issue is not something we are using (it is an optional webui for pouchdb) it is simple to remove all references to it and allow us to build. It is a hacky fix, but it should be possible to automate this in the build scripts until the situation changes.
1. `rm node_modules/express-pouchdb/lib/routes/fauxton.js`
1. In `node_modules/express-pouchdb/package.json` remove reference to pouchdb-fauxton
1. Build as normal `npm run build-win32`

@dotarmin @ronag Which would you prefer to do? I shall be looking to the 'hacky' option for our fork anyway as we need express-pouchdb

**Comment by ronag** [comment]
Remove the broken stuff in the build command.
