### ISSUE TITLE
Media Scanner /cls issue [Ubuntu 18.04]

### ISSUE THREAD

**Issue by vasudevavarun** [CasparCG/media-scanner#28]
Hi,
We are not able to get list of media files, While we can see templates without any issue.
Is this a known bug or anything through which we can resolve it?
Host: Ubuntu-18.04 64Bit

![image](https://user-images.githubusercontent.com/16715755/46206269-12c52280-c341-11e8-8284-bdaee798b7d5.png)

**Comment by Julusian** [comment]
Do you have ffmpeg installed on your system?

**Comment by thomasslee97** [comment]
I just encountered this issue. Fixed it with `chmod -R 775 SERVER_DIRECTORY` then deleted the _media folder and reran scanner

**Comment by Julusian** [comment]
@dotarmin in my opinion running that command is a workaround, not a good solution. It should be possible to make it work without needing to do that, or at least document a more correct command that doesnt change properties on every file inside the server folder

@vasudevavarun or @thomasslee97 did you simply follow the build steps in the readme and then execute it?

**Comment by dotarmin** [comment]
@Julusian I totally agree. Have any idea on a solution or do you know what properties are modified? I haven't run the server and scanner on 18.04 LTS that much but I will start doing some tests nearest future. 

Thanks for your work :)

**Comment by medcelerate** [comment]
If running mediascanner in docker I can confirm I have this issue too. No media appears when added to the media volume mounted.

**Comment by Julusian** [comment]
The `chmod` is not needed with the latest builds, so I think this is resolved
