### ISSUE TITLE
Leveldown node version

### ISSUE THREAD

**Issue by ronag** [CasparCG/media-scanner#3]
![untitled](https://user-images.githubusercontent.com/3065230/36314200-5f135b56-1334-11e8-8b43-68ed3a82ad53.png)

**Comment by pkeuter** [comment]
@ronag Did you do an npm install before building?

**Comment by ronag** [comment]
Yes

**Comment by pkeuter** [comment]
Issue was an outdated nodejs version. Version 8 is necessary because pkg builds in Node 8 context.
