### ISSUE TITLE
Some .mpg files wrongly identified as audio

### ISSUE THREAD

**Issue by m0vse** [CasparCG/media-scanner#40]
I had a show yesterday and copied some .mpg files (1920x1080 25fps) into the media directory. I then couldn't find them in the CasparCG client under the video section. Eventually I noticed that they had appeared in the audio section so had been wrongly identified (this happened to 3 out of 10 files). 

When I loaded them into the client, the videos played fine.

**Comment by m0vse** [comment]
After further investigation and running ffprobe on both working and non-working files, it appears that the files that are being identified as AUDIO, have the audio (AAC) stream first whereas the ones correctly identified as VIDEO have the video stream (H264) first.

Having examined the code in scanner.js, it only looks at the first stream, maybe it should iterate through all streams until it finds valid video?

**Comment by dotarmin** [comment]
Check PR #41, will be merged asap.

**Comment by dotarmin** [comment]
@m0vse, just realized it was you who submitted PR #41 😄

**Comment by STL1811** [comment]
I reproduce the same issue with video .MOV recorded with iPad. stream audio is #0 and stream video is #1. So media scanner tells that it's an AUDIO type.

**Comment by grahamspr86** [comment]
This pull request might resolve it, did for me. https://github.com/CasparCG/media-scanner/pull/41

**Comment by taurojo** [comment]
grahamspr86 not work for me  [#41](https://github.com/CasparCG/media-scanner/pull/41)
[FileVideo](https://casparcgforum.org/t/video-detects-as-audio-cinf/3279)

> This pull request might resolve it, did for me. #41

**Comment by Julusian** [comment]
This should be fixed in https://github.com/CasparCG/media-scanner/releases/tag/v1.2.0
