### ISSUE TITLE
CLS time reported is inconsistent with Thumbnail time

### ISSUE THREAD

**Issue by jpc0** [CasparCG/media-scanner#58]
The time reported by the `CLS` class [here](https://github.com/CasparCG/media-scanner/blob/1ce6cc7c828ffc22101c6457c9addf5aa269c128/src/scanner.js#L224) is in the format `YYYYMMDDHHmmss` whereas the time reported by `thumbnail list` [here](https://github.com/CasparCG/media-scanner/blob/1ce6cc7c828ffc22101c6457c9addf5aa269c128/src/scanner.js#L168) is in the ISO format `YYYYMMDDTHHmmss`.

Is there any specific reason for that? I am currently working on a parser for AMCP as a project and this combined with the lack of documentation on what the actual fields returned by these commands makes this harder than it needs to be.

I can submit a PR to fix it but unsure about whether this is even a bug in the first place, that and I would literally be submitting a PR to add a T to a source file...

**Comment by jpc0** [comment]
Concidering these were both submitted in commit [effd9e2](https://github.com/CasparCG/media-scanner/commit/effd9e2bf4d5021e6e9f398a770adac519f071a9) by @ronag maybe he has more insight? Possibly just a typo?

**Comment by jpc0** [comment]
@Julusian Concidering this file was touched by commits for the V1.1.0 release can I assume this is expected behaviour and close this issue?

**Comment by Julusian** [comment]
I would expect this to not be intentional, but I dont know

**Comment by jpc0** [comment]
Thanks for the reply. Since it has been in the codebase for some time it may be possible that it is concidered part of the API that it returns data in this manner. I'm going to close since I'm not entirely sure it's worth the hassle of a breaking change. I've updated the doc to show this as the output.
