### ISSUE TITLE
How to build SCANNER

### ISSUE THREAD

**Issue by MauriceVeraart** [CasparCG/media-scanner#6]
self explaining title i guess ?

can somebody make  a readme / how to build for the more
novice people around here.

**Comment by jesperstarkar** [comment]
You'll need Node and NPM installed and working.

1) Clone repo
2) cd to the root of repo
3) run `npm install`
3) run `npm run build-win32`

scanner.exe should then appear in sub-folder `/dist`

**Comment by MauriceVeraart** [comment]
Thanks jesper !!

```
> scanner@1.0.0 build-win32 C:\Users\MVE-DEV\Desktop\media-scanner
> (rmdir /s /q dist || true) && mkdir dist && pkg -t node8-win src/index.js -o dist/scanner.exe && cp node_modules/leveldown/build/Release/leveldown.node dist/

The system cannot find the file specified.
'true' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scanner@1.0.0 build-win32: `(rmdir /s /q dist || true) && mkdir dist && pkg -t node8-win src/index.js -o dist/scanner.exe && cp node_modules/leveldown/build/Release/leveldown.node dist/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scanner@1.0.0 build-win32 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MVE-DEV\AppData\Roaming\npm-cache\_logs\2018-02-21T14_02_42_215Z-debug.log
```

this did not work out for me see output above

ls

**Comment by ronag** [comment]
you need to run in in cygwin or git bash

**Comment by jesperstarkar** [comment]
An requirement of `pkg` or just due to the syntax used in the `build-wind32`-command?

**Comment by ronag** [comment]
@jesperstarkar just the syntax in build-win32

**Comment by MauriceVeraart** [comment]
ok thanks for the quick response really really appreciated by a dummy like me ;)

scanner now builded nicely took the wild guess to copy it into the folder where casparcg is ;)

I see familiar path's coming up in "the node" window

```
[2018-02-21T14:33:15.619Z] INFO (scanner/11412 on DESKTOP-04E1B90):
    caspar: {
      "config": "./casparcg.config"
    }
    paths: {
      "template": "template/",
      "media": "media/",
      "font": "font/",
      "ffmpeg": "ffmpeg.exe",
      "ffprobe": "ffprobe.exe",
      "log": "log/",
      "data": "data/"
    }
    scanner: {
      "paths": "media/"
    }
    thumbnails: {
      "width": 256,
      "height": -1
    }
    isProduction: false
    logger: {
      "level": "trace",
      "name": "scanner",
      "prettyPrint": true
    }
    http: {
      "port": 8000
    }
```

and CLS answers with
#200 CLS OK

but no files appear although I copied AMB to the media folder

I guess I am pretty close :( 
sorry for bothering you all

**Comment by ronag** [comment]
You need to start the scanner from the same folder as it is in so the working directory is correct. As you can see from the config the default is relative paths.

**Comment by MauriceVeraart** [comment]
ok 
I don't get it
scanner only works in the same dir as CasparCG
I guess that's because otherwise the node app does not see the folders when starting

when I add files to the media folder I see  reaction in node
when I CLS in the caspar console  i see reaction in node
when I Refresh in the casparClient i see reaction in node

but no list ;(

**Comment by MauriceVeraart** [comment]
does it need the path too ffmpeg to function ?

**Comment by baltedewit** [comment]
> does it need the path too ffmpeg to function ?

yup, since it uses ffprobe for media analysis.

**Comment by MauriceVeraart** [comment]
Thanks works now
