### ISSUE TITLE
Can't list media files

### ISSUE THREAD

**Issue by 5opr4ni** [CasparCG/media-scanner#60]
Hi

Maybe I am doing it all wrong, but can't get the new media scanner to work with casparcg-server-f081547e1d38ccf713659e22793d0cdbce8fa79b-windows

I downloaded the 1.1.0 and put the scanner.exe and the folder prebuilds in the casparcg-server-...... folder.
In casparcg.config i have this:
```
    <paths>
        <media-path>c:\\caspar\\_MEDIA\\</media-path>
        <log-path>c:\\caspar\\_LOG\\</log-path>
        <data-path>c:\\caspar\\_DATA\\</data-path>
        <template-path>c:\\caspar\\</template-path>
    </paths>
```
as we have normally
After that the only thing that works i TLS

What am I doing wrong?

Will the scanner be put in the caspar server folder in the next server release?

Swedish characters åäö in names don't work. Maybe a server issue.

Keep up the fantastic work you are doing.

/olle

**Comment by Julusian** [comment]
> After that the only thing that works i TLS
> What am I doing wrong?

Does it output any errors in the log when doing the `CLS`?

I didn't test this with caspar, but I did make sure that `http://localhost:8000/cls` produced some sensible looking result, which I thought would be a good enough test.

> Will the scanner be put in the caspar server folder in the next server release?

Yeah, before the next release I need to update the server workflow to pull in the scanner again.

> Swedish characters åäö in names don't work. Maybe a server issue.

I have a feeling there are some weird bugs around those. I remember writing https://github.com/CasparCG/server/issues/1018, and I wouldnt be surprised if the scanner can handle changing the case correctly, causing things to break.

**Comment by 5opr4ni** [comment]
> Does it output any errors in the log when doing the `CLS`?
No! Just
200 CLS OK

TLS works as expected


> Yeah, before the next release I need to update the server workflow to pull in the scanner again.
SUPER!


> I have a feeling there are some weird bugs around those. I remember writing [CasparCG/server#1018](https://github.com/CasparCG/server/issues/1018), and I wouldnt be surprised if the scanner can handle changing the case correctly, causing things to break.

Looked at that one and independent of case, it doesn't work with Swedish characters.

**Comment by Julusian** [comment]
@rjames1295 it looks like you havent provided a copy of `ffmpeg.exe`. Neither these scanner builds or casparcg-server will be including that currently

**Comment by rjames1295** [comment]
> @rjames1295 it looks like you havent provided a copy of `ffmpeg.exe`. Neither these scanner builds or casparcg-server will be including that currently

This actually lead me in the right direction, dropped in a ffmpeg.exe and ffprobe.exe into CasparCG's directory and the media files now show up.

Thank you!

**Comment by 5opr4ni** [comment]
Hahaha!

Sorry, ffmpeg and probe was the issue for me too, sorry for not checking the scanner log. :(
But Swedish characters is an issue. Do you want me to make an issue with that Julian?

/olle
